# Generated by Django 3.2.10 on 2021-12-13 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_school'),
        ('staff', '0002_auto_20211213_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.school'),
        ),
    ]
