# Generated by Django 3.2.10 on 2021-12-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20211219_2259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Appointment',
        ),
    ]
