# Generated by Django 3.2.10 on 2022-01-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('core', 'Core'), ('elective', 'Elective')], max_length=64, verbose_name='type'),
        ),
        migrations.DeleteModel(
            name='ClassType',
        ),
    ]
