# Generated by Django 3.2.10 on 2022-01-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0002_auto_20220105_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='gradebook.year'),
            preserve_default=False,
        ),
    ]
