# Generated by Django 3.2.10 on 2022-01-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_image'),
        ('gradebook', '0002_alter_class_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
