# Generated by Django 3.2.10 on 2022-01-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0003_auto_20220103_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject_type',
            field=models.CharField(choices=[('core', 'Core'), ('elective', 'Elective')], default='core', max_length=16),
            preserve_default=False,
        ),
    ]
