# Generated by Django 3.2.10 on 2022-01-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20220106_1611'),
        ('gradebook', '0003_term_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student', unique=True),
        ),
    ]
