# Generated by Django 3.2.10 on 2022-01-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0004_class_subject_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('subject', 'subject_type', 'term')},
        ),
    ]
