# Generated by Django 3.2.10 on 2022-01-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0005_alter_class_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
    ]
