# Generated by Django 3.2.10 on 2022-01-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20220101_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Form 1'), (2, 'Form 2'), (3, 'Form 3')]),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
