# Generated by Django 3.2.10 on 2022-01-01 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_school'),
        ('students', '0004_auto_20220101_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=64)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='core.school')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
