# Generated by Django 3.2.10 on 2022-01-01 14:57

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20220101_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to=students.models.img_file_path),
        ),
    ]
