# Generated by Django 3.2.9 on 2021-12-10 15:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211210_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('motto', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=16)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('logo', models.ImageField(blank=True, upload_to=core.models.img_file_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=64)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
