# Generated by Django 3.2.10 on 2021-12-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('id',)},
        ),
    ]
